site_name: IKIM Cluster
copyright: Copyright &copy; 2021 Institut für künstliche Intelligenz in der Medizin (IKIM), Essen

theme:
  name: material
  features:
    - navigation.sections

markdown_extensions:
  - footnotes
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets

nav:
  - Introduction: index.md
  - Getting Started:
     - For Researchers: researchers.md
     - For Students: students.md
  - User Guide:
     - Conda and Mamba: conda.md
     - Jupyter Notebooks: jupyter.md
     - FAQs: faq.md
